<?php

/**
 * @file
 * Primary module hooks for farmOS LOOC-C module.
 */

use Drupal\asset\Entity\AssetInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function farm_loocc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'farm_loocc.cobenefits':
      $output = [
        '#markup' => t('Select a method to view associated farm co-benefits and disbenefits.') . ' ' . t('For more information about these methods see the <a href=":link">Emissions Reduction Fund (ERF)</a>.', [':link' => 'http://www.cleanenergyregulator.gov.au/ERF']),
      ];
      return $output;
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function farm_loocc_asset_update(AssetInterface $asset) {

  // Bail if there is no original asset.
  if (empty($asset->original)) {
    return;
  }

  // Delete estimates if the asset is now archived.
  if ($asset->get('status')->value == 'archived' && $asset->original->get('status')->value != 'archived') {
    /** @var \Drupal\farm_loocc\LooccEstimateInterface $loocc_estimate */
    $loocc_estimate = \Drupal::service('farm_loocc.estimate');
    $loocc_estimate->deleteEstimate($asset);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function farm_loocc_asset_delete(AssetInterface $asset) {
  /** @var \Drupal\farm_loocc\LooccEstimateInterface $loocc_estimate */
  $loocc_estimate = \Drupal::service('farm_loocc.estimate');
  $loocc_estimate->deleteEstimate($asset);
}
